# Generated by Django 2.2.12 on 2020-05-26 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_event',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_events', to='blog.Event'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='blog.Comment_event')),
            ],
        ),
    ]
