# Generated by Django 2.2.12 on 2020-05-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
