# Generated by Django 2.2.12 on 2020-06-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200602_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='is_liked',
        ),
    ]
