# Generated by Django 2.2.12 on 2020-06-02 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_remove_picture_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='likes_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
